# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

jobs:
- job:
  steps:
  - task: UiPathPack@4
    inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'EnableIncognitoMode/project.json'
    outputType: 'Process'
    orchestratorConnection: 'DevopsSC'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- job:
  steps:
    - task: UiPathDeploy@4
      inputs:
      orchestratorConnection: 'DevopsSC'
      packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
      folderName: 'Test\Pipeline-test'
      entryPoints: 'EnableIncognitoMode.xaml'